Add algotirhm LCA, manacher, inverse pair count calculator
moonbit-community/Algorithms-Moonbit pull request #4
Opened 2024-12-16 16:32 UTC by smallbearrr

2024-12-16 16:36 UTC, smallbearrr commented
it checked failed, what should i change that can let it pass the check? @Lampese

2024-12-16 16:38 UTC, Lampese commented
> it checked failed, what should i change that can let it pass the check? @Lampese 

I will start to repair the Action, which will not affect the review of pr.

2024-12-20 13:19 UTC, Lampese requested changes

2024-12-20 13:19 UTC, Lampese commented on inversePair/inversePair_test.mbt
> +}
Did you use `moon fmt`?

2024-12-20 13:19 UTC, Lampese commented on inversePair/inversePair.mbt
> +fn merge[T : Compare](a : Array[T], b : Array[T], l : Int, r : Int) -> Int {
Filename should use snake format like `inverse_pair`.

2024-12-23 09:30 UTC, merged